# Generated by Django 5.1.15 on 2026-03-29 00:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GeneralNotification",
            fields=[
                (
                    "notification_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("recipient_account_id", models.UUIDField(db_index=True)),
                ("category", models.CharField(max_length=32)),
                ("source_type", models.CharField(blank=True, max_length=32)),
                ("source_ref", models.CharField(blank=True, max_length=128)),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unread", "unread"),
                            ("read", "read"),
                            ("archived", "archived"),
                        ],
                        default="unread",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ("-created_at", "notification_id"),
            },
        ),
        migrations.CreateModel(
            name="PushTokenRegistration",
            fields=[
                (
                    "push_token_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("account_id", models.UUIDField(db_index=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[("fcm", "fcm")], default="fcm", max_length=16
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("android", "android"),
                            ("ios", "ios"),
                            ("web", "web"),
                        ],
                        max_length=16,
                    ),
                ),
                ("device_key", models.CharField(max_length=64)),
                ("registration_token", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("app_version", models.CharField(blank=True, max_length=32)),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-updated_at", "push_token_id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("account_id", "device_key"),
                        name="uniq_notification_token_account_device",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PushDeliveryLog",
            fields=[
                (
                    "delivery_log_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("target_account_id", models.UUIDField(db_index=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[("fcm", "fcm")], default="fcm", max_length=16
                    ),
                ),
                ("event_type", models.CharField(max_length=64)),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField()),
                (
                    "delivery_status",
                    models.CharField(
                        choices=[
                            ("simulated_sent", "simulated_sent"),
                            ("failed", "failed"),
                        ],
                        max_length=32,
                    ),
                ),
                ("provider_message_id", models.CharField(blank=True, max_length=128)),
                ("failure_reason", models.CharField(blank=True, max_length=255)),
                ("requested_by_account_id", models.UUIDField()),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "inbox_notification",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delivery_logs",
                        to="notifications.generalnotification",
                    ),
                ),
                (
                    "push_token",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delivery_logs",
                        to="notifications.pushtokenregistration",
                    ),
                ),
            ],
            options={
                "ordering": ("-requested_at", "delivery_log_id"),
            },
        ),
    ]
